import React from 'react'

const Home = () => {
  return (
    <div>
        <h2 className="pb-2 fs-4">This is Home page</h2>
        <p>Lorem ipsum dolor sit amet  Lorem ipsum dolor sit amet consectetur adipisicing elit. Id quaerat rem adipisci esse ipsa aliquam eos suscipit veritatis quos eaque labore quo laborum consequatur placeat odio laudantium temporibus dolore voluptatum aliquid, earum quis eum. Expedita eius reiciendis obcaecati doloremque recusandae, ducimus quae sapiente animi earum eligendi, tenetur ut consectetur in exercitationem unde sunt itaque laudantium. Aliquam fuga nihil libero, voluptate fugiat inventore saepe nemo velit officia sint odio excepturi, delectus reiciendis est maiores ut recusandae. Tenetur, hic eum quis voluptate tempora sit asperiores sapiente accusantium ratione ad eaque delectus eveniet dignissimos eligendi aliquid assumenda corrupti, distinctio aperiam, facilis odit debitis? adipisicing elit. Laborum, ipsa dignissimos reiciendis in exercitationem commodi dolor. Excepturi culpa rem, tenetur iste mollitia non illo, similique fugiat laboriosam cupiditate cum illum explicabo. Aperiam at sed, vitae esse aspernatur adipisci libero error excepturi atque officia? Qui ipsam, doloremque eius dolorem delectus non, suscipit ipsa itaque iure reprehenderit inventore asperiores harum maiores et perspiciatis eligendi saepe quis laborum cum exercitationem nostrum praesentium dolore! Qui maxime ut nostrum voluptatibus eum, veritatis cupiditate quos quisquam commodi minima id aliquid accusantium sunt perferendis repellat ad veniam iure laborum assumenda odit impedit provident quasi corporis? Ex possimus commodi perspiciatis aut exercitationem repudiandae corporis cupiditate pariatur impedit, obcaecati consectetur libero molestiae modi nobis blanditiis atque eius, quas asperiores. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex molestiae est asperiores dolorem dicta, ratione ipsa harum maiores ab similique reiciendis assumenda quae, dolore unde, maxime earum nam officiis aspernatur quis blanditiis accusamus? Quas laboriosam reprehenderit voluptas deserunt minima dolores maiores, laborum fugit natus iure voluptatibus asperiores quisquam neque molestias fugiat tempore et, nesciunt culpa aperiam eligendi officia autem aspernatur corporis? Harum vitae alias quaerat sapiente perspiciatis dolore. Laudantium laboriosam explicabo alias ullam quaerat ea nesciunt iste, earum tempore quia tenetur exercitationem hic perspiciatis laborum sequi voluptatum? Libero, facilis commodi, at sint amet nisi nulla dolorem ex sit, officiis quod.</p>
    </div>
  )
}

export default Home
